es_name: "PGPE"
problem_type: "gridworld_recipes_reward_item"
normalize: false
es_config:
  pop_size: 200
  center_learning_rate: 0.01
  stdev_learning_rate: 0.07
  init_stdev: 0.04
  optimizer: "adam"
policy: "MetaRNN2"
hidden_size: 128
hidden_size_2: 64
num_tests: 128
n_repeats: 16
max_iter: 2000
test_interval: 100
log_interval: 20
seed: 5
gpu_id: [0, 1]
debug: false
spawn_prob: 0.005
model_dir: ""