es_name: "OpenES"
problem_type: "gridworld_recipes"
#problem_type: "gridworld_recipes_reward_item"
normalize: false
es_config:
  pop_size: 200
  init_stdev: 0.07
  decay_stdev: 0.9998
  limit_stdev: 0.01
  optimizer: "adam"
  optimizer_config:
    lrate_init: 0.02
    lrate_decay: 0.9998
    lrate_limit: 0.001
    momentum: 0.0
policy: "MetaRNN2"
hidden_size: 5
hidden_size_2: 64
hidden_layers: [64]
num_tests: 100
n_repeats: 128
max_iter: 8000
test_interval: 100
log_interval: 25
seed: 1
gpu_id: [0,1]
debug: false
spawn_prob: 0.005
model_dir: ""
